apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-volume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: bitnami/wordpress-nginx:6.1.1
          ports:
          - containerPort: 8080
            name: wordpress
          volumeMounts:
            - name: wordpress-data
              mountPath: /bitnami/wordpress
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: yes
            - name: WORDPRESS_DATABASE_HOST
              value: mysql-service.default.svc.cluster.local
            - name: WORDPRESS_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: WORDPRESS_DATABASE_USER
              value: root
            - name: WORDPRESS_DATABASE_NAME
              value: wordpress
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wordpress-volume

---

kind: Service
apiVersion: v1
metadata:
  name: wordpress-service
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
